### ISSUE TITLE
Portal Not Generating

### ISSUE THREAD

**Issue by beareogaming** [Shinoow/The-Beneath#10]
Minecraft; 1.12.2
SpongeAPI 7.1.0-SNAPSHOT-43d8496
SpongeForge 1.12.2-2690-7.1.0-BETA-3115
Minecraft Forge: 14.23.3.2679

Using the Sevtech Ages Modpack Current Version

Apon entering the beneath a portal is not made and the player suffocates in a wall.
Apon exiting the beneath using a portal you are returned to the original portal and torches are placed around the original portal placed to enter the beneath.
along with entering/leaving the dimension the following appears in console
[https://pastebin.com/2VMLeyzE](url)

**Comment by beareogaming** [comment]
ive noticed that regardless of the dimension you enter, even logging in, That pastebin error occures.
So no errors are thrown yet it doesnt spawn a platform on the inside of the beneath

**Comment by Shinoow** [comment]
The behavior you're describing is the exact inverse of the teleportation logic. Can you reproduce this without Sponge?
Also, that error is thrown from Journeymap.

**Comment by Shinoow** [comment]
Did you by chance enter the Beneath from any dimension other than the Overworld?

**Comment by beareogaming** [comment]
I cannot reproduce it without sponge, i have no idea what would cause
sponge to do it but i assumed it was sponge

**Comment by Pixelmnkey** [comment]
Same issue here, using sponge won't spawn the return block. Should we post in sponge?

**Comment by beareogaming** [comment]
Sorry I missed your second msg. No I tried it from the overworld

**Comment by Shinoow** [comment]
Once it's approved, 1.4.2 could _potentially_ fix this, no promises though. If the small change I made there has no effect, then it's something that has to be patched on Sponge's end.

**Comment by Shinoow** [comment]
Closing this for now. If it's still happening, you might wanna report it to Sponge.
