### ISSUE TITLE
[Feature Request] Changing Darkness Damage - More Options 

### ISSUE THREAD

**Issue by MokahTGS** [Shinoow/The-Beneath#14]
Still taking damage even when I have the game mode set to Grue in the configs.  I'm not using the grue mod, but I shouldn't take damage right?  There needs to be a way to turn darkness damage off in the configs.

**Comment by Shinoow** [comment]
If Grue isn't installed it defaults back to darkness if set to Grue. Currently it's one or the other, always one hazard in the darkness.

**Comment by MokahTGS** [comment]
Yes but as mod pack makers we should have control over the damage amounts...like 0 as a minimum instead of 2.

I'm using Lycanites mobs for darkness mob spawning.  I guess ill just have to find another cave dimension mod.

**Comment by Shinoow** [comment]
The thing is, when I was commissioned to make this mod, there was no intent of it ever being safe being in the darkness, hence the shadows pulling you in and there always being something hurting you in the dark (whether or was from being in the dark, or getting attacked by a Grue).
But feature requests are also a thing, you know?

**Comment by MokahTGS** [comment]
OK, then can I change this to a feature request?  Specifically either a third option for the dimension that has no darkness damage, or changing the minimum damage dealt to 0 instead of 2.

Just so you know, I have no intention of this dimension being safe.  It's anything but safe.  I'm just using another mod to provide the darkness monster generation.  I need this because those monsters are needed for other reasons.  I'm tying all these mods together.

The Grue mod is not what I need.  It is buggy, and basically a one trick pony.  Lycanites Mobs provide a much finer grain spawning mechanic that allows me to do things that I can't do any other way.

I just don't need the invisible force doing the damage...there are plenty of other things to do that.

**Comment by Shinoow** [comment]
Just out of curiosity, in what way is Grue buggy?

**Comment by MokahTGS** [comment]
It spawns even when you blacklist the dimension plus they keep spawning.  As if one unkillable superfast monster isnt enough.

**Comment by Shinoow** [comment]
>It spawns even when you blacklist the dimension

If you blacklist the Beneath with the mode set to grue, it's gonna override whatever Grue has defined in it's config.
The spawning seems like a non-issue to me. If one has spawned and you're still not placing down a torch or getting out of the dark, maybe you should do one of those. Then again, with wimp mode on, that could certainly become a nuisance when they can't kill you in one hit.

**Comment by MokahTGS** [comment]
I'm not asking about the spawning...I'm just not using the Grue mod because of the above issues.  I would like the beneath config adjusted to allow for no darkness damage if a mod pack maker wants to do that.

**Comment by MokahTGS** [comment]
Thank you!  :)
