### ISSUE TITLE
Oregen text disappearing

### ISSUE THREAD

**Issue by jordanasch** [Shinoow/The-Beneath#2]
Hey Shinoow

Every time I try to add any ores from Gemcraft the oregen gets wiped.
"https://minecraft.curseforge.com/projects/gem-craft"

Thanks Aschy

**Comment by Shinoow** [comment]
Can you show me how your oregen.json file looks like (before launching, that is)? The file getting wiped usually means the JSON format was malformed.

**Comment by jordanasch** [comment]
[
  {
    "ore": "minecraft:coal_ore",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 32,
    "size": 16,
    "miny": 10,
    "maxy": 246
  },
  {
    "ore": "minecraft:iron_ore",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 24,
    "size": 16,
    "miny": 10,
    "maxy": 246
  },
  {
    "ore": "minecraft:lapis_ore",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 12,
    "size": 8,
    "miny": 10,
    "maxy": 246
  },
  {
    "ore": "minecraft:redstone_ore",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 12,
    "size": 12,
    "miny": 10,
    "maxy": 246
  },
  {
    "ore": "minecraft:gold_ore",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 8,
    "size": 8,
    "miny": 10,
    "maxy": 246
  },
  {
    "ore": "minecraft:diamond_ore",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 4,
    "size": 8,
    "miny": 10,
    "maxy": 246
  },
  {
    "ore": "minecraft:emerald_ore",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 2,
    "size": 4,
    "miny": 10,
    "maxy": 246
  },
  {
    "ore": "minecraft:monster_egg",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 48,
    "size": 24,
    "miny": 10,
    "maxy": 246
  }
  {
    "ore": "gemcraft:BlockSapphireOre",
    "oremeta": 0,
    "source": "minecraft:stone",
    "srcmeta": 0,
    "veins": 24,
    "size": 16,
    "miny": 10,
    "maxy": 246
  }
]

**Comment by Shinoow** [comment]
There's no comma to separate the second to last and last entry, needs to be a comma after the closing `}` of the `minecraft:monster_egg` entry.

**Comment by jordanasch** [comment]
Thank you so much, I can't believe it was something so small! I now am getting so much closer to finishing my mod pack! I hope you don't mind I'm using it in my mod pack and its just a private mod pack and I have changed a couple of textures to suit it a little bit as I am not into like ghosts or anything.

**Comment by Shinoow** [comment]
Making the shadows visible ruins the immersion of the mod (since shadows are shadows, they're meant to be next to invisible in complete darkness). But hey, if you don't like that, I can't stop you from changing it.

**Comment by jordanasch** [comment]
I actually did quite the opposite, I made them completely invisible so its more of just a random event when it pulls you back and got rid of the hand just because I prefer to completely remove any elements from mods pertaining to the occult. It will fit better with my mod pack too as the story revolves around data/viruses/etc. Thanks for being a little understanding, I absolutely would not distribute my mod pack publicly without your consent(Which I don't know if would even happen anyway, and it would just be so that it is easier for my friends to install the mod pack.)

**Comment by Shinoow** [comment]
Oh, I see.
As long as you follow the modpack terms, you're free to include the mod in said modpack.

**Comment by jordanasch** [comment]
I haven't had a chance to test the difficulty yet and I have lots of mods to improve the difficulty, and I love that you included the bonus health on mobs because this mod for me is a post-end-endgame. But if I had any suggestions I would say included a config option for adding more health, etc to increase the difficulty even more. But I think I'm one of the few who actually want minecraft more difficult :P

**Comment by Shinoow** [comment]
Configurable health and damage boost is now implemented as of 1.3.0.
