### ISSUE TITLE
Inventory Flickers when in Beneath

### ISSUE THREAD

**Issue by CalaMariGold** [Shinoow/The-Beneath#21]
#### Description:

Inventory slightly flickers when in the Beneath. This mod is apart of my modpack and probably not because of the Beneath itself, but I'm just wondering what you think could be causing it.

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal
- The Beneath: 1.6.0

**Comment by Shinoow** [comment]
Shaders? Could be some mod that changes the UI. If you could drop a modlist, I could make a better guess.

**Comment by CalaMariGold** [comment]
https://www.curseforge.com/minecraft/modpacks/rebirth-of-the-night/relations/dependencies

**Comment by Shinoow** [comment]
I tried running the modpack without any modifications to it, with Optifine installed without a shader, and with Optifine along with Sildur's Enhanced Default Shader. I didn't get any flickering in either of the cases.
Might be a combination of setting changes and shader settings that results in the flickering, but I can't reproduce it with default settings.

**Comment by CalaMariGold** [comment]
I see. I'll try messing with the settings then. Thank you for testing it!
