### ISSUE TITLE
Request: Support for modded cave generation

### ISSUE THREAD

**Issue by yungnickyoung** [Shinoow/The-Beneath#22]
Currently, it looks like The Beneath supports modded worlgen using `onChunkPopulate`:
https://github.com/Shinoow/The-Beneath/blob/df7afb88c565273a59ebca49d0bbedddea281110/src/main/java/com/shinoow/beneath/common/world/gen/ChunkProviderDeepDank.java#L373
or `DecorateBiomeEvent`:
https://github.com/Shinoow/The-Beneath/blob/df7afb88c565273a59ebca49d0bbedddea281110/src/main/java/com/shinoow/beneath/common/world/gen/ChunkProviderDeepDank.java#L379

It would be great if you could add support for modded cave gen as well.
Currently, cave gen for The Beneath is initialized at declaration:
https://github.com/Shinoow/The-Beneath/blob/df7afb88c565273a59ebca49d0bbedddea281110/src/main/java/com/shinoow/beneath/common/world/gen/ChunkProviderDeepDank.java#L56

Instead, maybe something like the following could be done in the constructor:
```java
public ChunkProviderDeepDank(World worldIn, long seed)
{
    ...
    genDankCaves = new MapGenCavesDeepDank();
    genDankCaves = net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(genDankCaves, net.minecraftforge.event.terraingen.InitMapGenEvent.EventType.CAVE);
    ...
}
```

I haven't tested this, but I would think the actual fix would be similarly simple, if not exactly what I wrote above.

Let me know what you think!

**Comment by forresthopkinsa** [comment]
So, can we use Yung's Better Caves with The Beneath 1.7.0? I'm not seeing a cavegen config option documented anywhere but a cursory glance at the commit above suggests that enabling third-party worldgen is sufficient.

**Comment by Shinoow** [comment]
Yes, enabling third-party worldgen does the trick.
