### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [Shinoow/The-Beneath#24]
#### Description:

Will you update the mod to newest version? 1.16.5 really popular and stable, such as 1.12.2 or 1.7.10

#### Affected versions:
- Minecraft: 1.16
- Forge: 1.16.5
- The Beneath: 1.0

**Comment by KlutzyBubbles** [comment]
Is there any plans to update the mod (I am also looking for 1.16.5)?

Just closing the issue doesn't answer the question.
