### ISSUE TITLE
With advanced rocketry The Beneath becomes a moon

### ISSUE THREAD

**Issue by tjsd** [Shinoow/The-Beneath#7]
Not sure if this is a The Beneath or Advanced Rocketry problem. But the dim gets created as a moon, even if I change the dimension id to something different it gets recreated as a moon. Requires oxygen and doesnt create propper.

The Beneath-1.12.2-1.3.0
AdvancedRocketry-1.12.2-1.2.6-27

**Comment by Shinoow** [comment]
That's Advanced Rocketry. I do believe someone has already reported it to the devs, and there may already be a fix out for it, but that mod somehow overrides dimension IDs (or simply has a fixed range it *assumes* are planets). There was some mention of it over at https://github.com/AllTheMods/ATM-3/issues/291, where by the looks of it the thing comes down to configuration (don't quote me on that, I only skimmed through the conversation).
