### ISSUE TITLE
[1.12.2] [Issue] Can't get the recipe to work.

### ISSUE THREAD

**Issue by BastionNtB** [Shinoow/The-Beneath#8]
I've tried many different things, here is what I've got in the config

    S:"Beneath Teleporter Crafting Recipe" <
        #&#
        &%&
        #&#
        #
        minecraft:concrete:15
        &
        chisel:voidstone:0
        %
        minecraft:skull:1
     >

And 

B:"Use Crafting Recipe"=true

I get no errors in the console that I know of...

What logs could I give you that would help, if any?

Is there something I'm doing wrong?

Just mainly looking for help, thanks :)

**Comment by Shinoow** [comment]
Did the default recipe work? The only thing that could be wrong there is `chisel:voidstone:0`, but that's only because I'm not familiar with the registry names Chisel has assigned to their blocks.

**Comment by Shinoow** [comment]
Closing this for now. Re-open if it's still a problem.
